// <auto-generated />
using BevPay.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BevPay.Infrastructure.Migrations
{
    [DbContext(typeof(BarContext))]
    partial class BarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BevPay.Core.Models.Beverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Beverage", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Blå Vand"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Spejlæg"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Øl"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
