@startuml bevpayapi
Actor Frontend as frontend
participant UserController as usercontroller
participant UserService as userserv
participant UserRepository as userrepo
database MySQL as database

hide footbox

== Login ==

frontend -> usercontroller: POST /auth/login
activate usercontroller
usercontroller -> userserv: Login(dto)
activate userserv
userserv -> userrepo: GetUserByUserName(dto.UserName)
activate userrepo
userrepo -> database: // Fetch a specific user from the database //
activate database
database --> userrepo
deactivate database
userrepo --> userserv: User
deactivate userrepo
alt user == null
userserv -> usercontroller:  throw new NotFoundException()
usercontroller --> frontend: 401 Unauthorized
end
userserv -> userserv: VerifyPassword(dto.Password, user.Password)
alt !correctPassword
userserv -> usercontroller: throw new WrongPasswordException()
usercontroller --> frontend: 401 Unauthorized
end
userserv --> usercontroller: User
deactivate userserv
usercontroller -> userserv: GenerateClaimsIdentity(userDto)
activate userserv
userserv --> usercontroller: claimsIdentity
deactivate userserv
usercontroller -> userserv: GenerateJwtToken(claimsIdentity)
activate userserv
userserv --> usercontroller: token
deactivate userserv
usercontroller -> usercontroller: Cookies.Append(token)
usercontroller --> frontend: 200 OK
deactivate usercontroller

== Logout ==

frontend -> usercontroller: POST /auth/logout
activate usercontroller
usercontroller -> userserv: DeleteToken() 
usercontroller --> frontend: 200 OK
deactivate usercontroller

@enduml